radarr:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host radarr.home.nathanshannon.net
          paths:
            - path: /
              pathType: Prefix 