paperless:
  ingress:
    main:
      enabled: false
      ingressClassName: nginx
      hosts:
        - host: &host paperless.host.nathanshannon.net
          paths:
            - path: /
              pathType: Prefix