homebridge:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host homebridge.home.nathanshannon.net
          paths:
            - path: /
              pathType: Prefix