home-assistant:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host home-assistant.home.nathanshannon.net
          paths:
            - path: /
              pathType: Prefix