nzbhydra2:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host nzbhydra2.home.nathanshannon.net
          paths:
            - path: /nzbhydra2
              pathType: Prefix