nzbhydra2:
  ingress:
    main:
      enabled: false
      ingressClassName: nginx
      hosts:
        - host: &host nzbhydra2.home.nathanshannon.net
          paths:
            - path: /
              pathType: Prefix